Aaron/roster
Aakup/MultiMeet pull request #14
Opened 2019-04-15 23:31 UTC by Aakup

2019-04-15 23:38 UTC, kev-chien requested changes
See merge conflict, otherwise looks good.

2019-04-15 23:38 UTC, kev-chien commented on app/views/projects/index.html.erb
> +<<<<<<< HEAD
unresolved merge conflict, I assume you want to keep the HEAD now

2019-04-15 23:54 UTC, kev-chien approved these changes

2019-04-16 00:13 UTC, lawrencechen14 approved these changes
Looks good. Great job Aaron!

2019-04-16 00:14 UTC, merged