Adding security feature
Aakup/MultiMeet pull request #51
Opened 2019-05-13 09:43 UTC by lawrencechen14

- Adding security measures to project, participant, and ranking controllers
- Added cuke tests

2019-05-13 20:47 UTC, kev-chien requested changes
Thanks so much for adding this! Can you try to make sure that anytime a user tries to access anything belonging to another user's project, the user is denied access? So e.g. for matching, and the redirect takes you to root or the projects page?

At least that makes the most sense to let me. Let me know your thoughts.

2019-05-13 20:47 UTC, kev-chien commented on app/controllers/participants_controller.rb
> +
Can you add this to every action? as a `before_action :ensure_owner_logged_in

2019-05-13 20:47 UTC, kev-chien commented on app/controllers/participants_controller.rb
> +    unless Participant.where(project_id: @project.id).ids.include? params[:id].to_i
instead of `Participant.where(project_id: @project.id)` do `@project.participants`

2019-05-13 20:47 UTC, kev-chien commented on app/controllers/projects_controller.rb
> +
Ditto for previous two comments

2019-05-14 05:20 UTC, kev-chien commented on app/controllers/participants_controller.rb
> +
Thanks for adding!

2019-05-14 05:20 UTC, kev-chien commented on app/controllers/participants_controller.rb
> +    unless Participant.where(project_id: @project.id).ids.include? params[:id].to_i
Thanks for adding!

2019-05-14 05:20 UTC, kev-chien commented on app/controllers/projects_controller.rb
> +
Thanks for adding!

2019-05-14 05:21 UTC, kev-chien commented on app/views/rankings/edit.html.erb
> +        <% @times_hash.keys.sort.each do |date|  %>
Good addition!

2019-05-14 05:21 UTC, kev-chien approved these changes

2019-05-14 21:25 UTC, Aakup approved these changes
Good job

2019-05-14 21:25 UTC, merged